apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ .Values.pvc.name }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: {{ .Values.pvc.size | default "1Gi" }}